import "./homepage.scss";

import type { Metadata } from "next";

import { Josefin_Sans, Montserrat } from "next/font/google";

const josefinSans = Josefin_Sans({
	subsets: ["latin"],
	variable: "--josefin-sans",
	display: "swap"
});

const montserrat = Montserrat({
	subsets: ["latin"],
	variable: "--montserrat",
	display: "swap",
})

export const metadata: Metadata = {
	title: "Next Project - Projects Manager",
	description: "Generated by create next app",
};

import { Header } from "./layout/Header";
import { Main } from "./layout/Main";
import {Footer} from "./layout/Footer";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={
            `${montserrat.className}
			${josefinSans.variable}
			${montserrat.variable}`
        }>
            <body>
                <Header />
                <Main>
                    <div className="homepage">
                        {children}
                    </div>
                </Main>
                <Footer />
            </body>
        </html>
    );
}