import "@/sass/main.scss";
import { ThemeContext } from "@/themes/ThemeContext";

import type { Metadata } from "next";

import { Josefin_Sans, Montserrat } from "next/font/google";

const josefinSans = Josefin_Sans({
	subsets: ["latin"],
	variable: "--josefin-sans",
	display: "swap"
});

const montserrat = Montserrat({
	subsets: ["latin"],
	variable: "--montserrat",
	display: "swap",
})

export const metadata: Metadata = {
	title: "Next Project - Projects Manager",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={
			`${montserrat.className}
			${josefinSans.variable}
			${montserrat.variable}`
		}>
			<ThemeContext>
				{children}
			</ThemeContext>
		</html>
	);
}
