import { Header } from "@/layout/Header";
import "@/sass/main.scss";
import { ThemeContext } from "@/themes/ThemeContext";

import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Next Project - Projects Manager",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeContext>
				<Header />
				{children}
			</ThemeContext>
		</html>
	);
}
